#!/usr/bin/env python3
"""Refresh data/publications.js from Google Scholar.

Usage:
    python scripts/fetch_publications.py

Rewrites data/publications.js in place — nothing else in the project is
touched.

Google Scholar has no official API; this uses the `scholarly` package to
scrape the public profile page. Scholar occasionally rate-limits or
CAPTCHA-blocks scrapers, especially from cloud/datacenter IPs (this
includes GitHub Actions runners). If a run fails, wait a while and retry,
or run it from your own machine instead.
"""

import json
import pathlib
import sys
import unicodedata

from scholarly import scholarly

SCHOLAR_USER_ID = "-hKl4UYAAAAJ"
OWNER_LASTNAME = "visona"  # matched with accents stripped, case-insensitive

DATA_PATH = pathlib.Path(__file__).resolve().parent.parent / "data" / "publications.js"


def strip_accents(text: str) -> str:
    normalized = unicodedata.normalize("NFKD", text)
    return "".join(ch for ch in normalized if not unicodedata.combining(ch))


def is_owner(author_name: str) -> bool:
    return OWNER_LASTNAME in strip_accents(author_name).lower()


def format_authors(author_field: str):
    # scholarly joins bib authors as "First Last and First Last and ..."
    names = [n.strip() for n in author_field.split(" and ") if n.strip()]
    return [{"name": n, **({"me": True} if is_owner(n) else {})} for n in names]


def fetch_publications():
    author = scholarly.search_author_id(SCHOLAR_USER_ID)
    author = scholarly.fill(author, sections=["publications"])

    profile_url = f"https://scholar.google.com/citations?hl=en&user={SCHOLAR_USER_ID}"
    results = []

    for pub_stub in author.get("publications", []):
        pub = scholarly.fill(pub_stub)
        bib = pub.get("bib", {})

        title = bib.get("title")
        year = bib.get("pub_year")
        if not title or not year:
            continue

        venue = bib.get("citation") or bib.get("journal") or ""
        author_field = bib.get("author", "")
        cited_by = pub.get("num_citations")

        results.append({
            "year": int(year),
            "title": title,
            "venue": venue,
            "citedBy": cited_by if cited_by else None,
            "link": pub.get("pub_url") or profile_url,
            "authors": format_authors(author_field),
        })

    results.sort(key=lambda p: p["year"], reverse=True)
    return results


def write_publications(pubs):
    new_json = json.dumps(pubs, indent=2, ensure_ascii=False)
    content = (
        "// Publications for the Teaching/Home publications list.\n"
        "// Regenerated by scripts/fetch_publications.py from Google Scholar —\n"
        "// hand edits to individual entries are fine, but the overall shape\n"
        "// (year/title/venue/citedBy/link/authors) should stay the same.\n"
        "window.PUBLICATIONS = " + new_json + "\n"
    )
    DATA_PATH.write_text(content, encoding="utf-8")


def main():
    pubs = fetch_publications()
    if not pubs:
        print("No publications found — leaving data/publications.js untouched.", file=sys.stderr)
        sys.exit(1)
    write_publications(pubs)
    print(f"Updated data/publications.js with {len(pubs)} publications.")


if __name__ == "__main__":
    main()
